### ISSUE TITLE
CORs causing post issues

### ISSUE THREAD

**Issue by tysonbul** [moadben/OpenCode#12]
CORS is making browsers not be able to make post requests to the server. This needs to be looked into on the server side. 
I believe the node server is fine and it's regarding the Golong server that needs to be configured possibly.

**Comment by moadben** [comment]
It's definitely an issue with communication between React and the Golang API, completely irrelevant to the Node server. The problem is the fact that even though the server and client are located on the same host machine, the fact that they aren't located on the same port means they don't share the same 'domain'. I need to update the server to accept CORS requests.
